[package]
name = "spirv-reflect-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
cc = "1"
bindgen = { version = "0.71", optional = true }

[features]
generate_bindings = ["bindgen"]
